version: 0.2

env:
  variables:
    NODE_ENV: "production"
    AWS_DEFAULT_REGION: "us-east-1"
    
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd frontend && npm ci
      - cd ../backend && npm ci
      - docker --version
      
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo "Running tests..."
      - cd backend && npm test
      
  build:
    commands:
      - echo "Building frontend..."
      - cd frontend && npm run build
      
      - echo "Building backend Docker image..."
      - cd ../backend
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REPOSITORY_URI:$IMAGE_TAG
      
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      
      - echo "Creating imagedefinitions.json for CodeDeploy..."
      - printf '[{"name":"backend","imageUri":"%s"}]' $ECR_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      
      - echo "Syncing frontend to S3..."
      - aws s3 sync ../frontend/dist/ s3://$FRONTEND_BUCKET --delete
      
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - backend/imagedefinitions.json
    - backend/Dockerfile
    - frontend/dist/**/*
  base-directory: .